# Neptune C-- custom filetype for Geany
# File name: filetypes.Neptune.conf

[styling=Python]
default=default
comment=comment
comment_line=comment_line
number=number
string=string
operator=operator
keyword=keyword
function=function
identifier=identifier
brace=brace

[keywords]
primary=var echo cin efunc return if else while for end vartable

[settings]
lexer_filetype=Python
extension=nep
comment_single=#
comment_use_indent=true

[build-menu]
FT_00_LB=_Compile
FT_00_CM=neptune "%f"
FT_00_WD=
EX_00_LB=_Execute
EX_00_CM=neptune "%f"
EX_00_WD=
