[styling=C]
default=default
comment=comment
commentline=comment_line
number=number
string=string
character=string
operator=operator
word=keyword
word2=keyword2
word3=keyword3
word4=keyword4
function=function
identifier=identifier
brace=brace

[keywords]
primary=var vartable struct efunc echo cin do end Include define
secondary=if else while for return true false
docComment=

[settings]
lexer_filetype=C
extension=nep
comment_single=#
comment_use_indent=false

[build-menu]
FT_00_LB=_Run Neptune
FT_00_CM=neptune "%f"
FT_00_WD=
