[styling=Lua]
default=default
comment=comment
commentline=comment_line
number=number
string=string
character=string
operator=operator
word=keyword
word2=keyword2
word3=keyword3
word4=keyword4
function=function
identifier=identifier
brace=brace

[keywords]
primary=var vartable struct true false
secondary=if else while for end do return include Include define
word3=efunc echo cin type length add remove clear upper lower contains replace substring read write append exists delete
word4=and or not

[settings]
lexer_filetype=Lua
extension=nep
comment_single=#
comment_use_indent=false
tag_parser=Lua

[build-menu]
FT_00_LB=_Run Neptune
FT_00_CM=neptune "%f"
FT_00_WD=
